# Generated by Django 5.2.4 on 2026-04-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_recruited',
            field=models.BooleanField(default=False),
        ),
    ]
