# Generated by Django 5.2.4 on 2026-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0002_agenttask_cancel_requested_agenttask_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='model_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='provider',
            field=models.CharField(default='ollama', max_length=40),
        ),
    ]
