# Generated by Django 6.0.4 on 2026-04-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0003_agenttask_model_name_agenttask_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
