# Generated by Django 5.2.4 on 2026-04-12 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_is_recruited'),
        ('tasking', '0004_agenttask_api_key_agenttask_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('initial_prompt', models.TextField()),
                ('status', models.CharField(choices=[('thinking', 'Manager Thinking'), ('delegating', 'Delegating Tasks'), ('reviewing', 'Reviewing Results'), ('awaiting_approval', 'Awaiting User Approval'), ('completed', 'Completed'), ('failed', 'Failed')], default='thinking', max_length=20)),
                ('final_result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_workflows', to='agents.agent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('read', 'Read')], default='pending', max_length=20)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_notifications', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasking.workflow')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('analysis', 'Manager Analysis'), ('recruitment', 'Agent Recruitment'), ('delegation', 'Task Delegation'), ('execution', 'Agent Execution'), ('review', 'Manager Review')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasking.workflow')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
