# Generated by Django 6.0.4 on 2026-04-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0006_providercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
