# Generated by Django 6.0.4 on 2026-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0008_workflow_error_message_workflow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='ollama_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
