# Generated by Django 6.0.4 on 2026-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0009_agenttask_ollama_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='default_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='default_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workflow',
            name='ollama_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
