# Generated by Django 6.0.4 on 2026-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0010_workflow_default_model_workflow_default_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='user_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
